name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
jobs: 
    update-readme-with-blog: 
        name: Latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
              with:
                token: ${{ secret.GH_TOKEN }}
            - uses: gautamkrishnar/blog-post-workflow@master
              env:
                GITHUB_TOKEN: ${{ secret.GH_TOKEN }}
              with:
                comment_tag_name: BLOG-POST-LIST
                max_post_count: "4"
                feed_list: "https://medium.com/feed/@prantoamt"
